# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180318_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
